
global_config:
  retrieval_path: "retrieval/rag_retrieval_indexes.json"
  wiki_path : "../../../data/wiki_dump2018_nq_open/processed/wiki.feather"
  embeder_path : "../../../models/llms/bge-base-en-v1.5"
  vector_db_path : "../../../data/wiki_dump2018_nq_open/wiki_ip.index"
  questions_path : "../50_test.feather"
  laguage_model_path : "../../../models/llms/Llama-3.2-3B-Instruct"
  model_run_id : "preview_50_IP"
  train_collection_id: "preview_50_IP_train_collection"
  test_collection_id: "preview_50_IP_test_collection"
  k : 4
  seed: 42
  size_index: 100
  num_models: 50

pre_collections_config:
  train_samples: 2000
  test_samples: 400
  tags: ["preview_50", "FAISS_IP"]
  train_start_idx: 0
  train_end_idx: 2000
  test_start_idx: 0
  test_end_idx: 400
  train_checkpoint: 200
  test_checkpoint: 200