
global_config:
  retrieval_path: "retrieval/rag_retrieval_indexes.json"
  wiki_path : "../../data/wiki_dump2018_nq_open/processed/wiki.feather"
  embeder_path : "../../models/llms/bge-base-en-v1.5"
  vector_db_path : "../../data/wiki_dump2018_nq_open/wiki2.index"
  questions_path : "questions.feather"
  laguage_model_path : "../../models/llms/Llama-3.2-3B-Instruct"
  model_run_id : "model_test"
  train_collection_id: "train_collection"
  test_collection_id: "test_collection"
  k : 4
  seed: 42
  size_index: 100
  num_models: 2

pre_collections_config:
  train_samples: 6
  test_samples: 4
  tags: ["test", "FAISS_L2"]
  train_start_idx: 0
  train_end_idx: 6
  test_start_idx: 0
  test_end_idx: 4
  train_checkpoint: 2
  test_checkpoint: 2